services:
  typo-emoji-service:
    container_name: typo-emoji-service
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    restart: unless-stopped
    volumes:
      - path-to-appsettings.json:/app/appsettings.json
    ports:
      - "5124:8080"